# Generated by Django 4.0.3 on 2022-03-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Designates whether this user's email is be verified.", verbose_name='verified'),
        ),
    ]
