# Generated by Django 4.0.3 on 2022-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_user_register_type_user_third_party_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='third_party_user_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='third party user_id'),
        ),
    ]
