# Generated by Django 4.0.3 on 2022-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_user_third_party_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='third_party_user_id',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True, verbose_name='third party user_id'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('register_type', 'third_party_user_id')},
        ),
    ]
